name: Check Ferry Availability

on:
  schedule:
    # Run every minute
    - cron: '* * * * *'
  workflow_dispatch:  # Allow manual triggers for testing

jobs:
  check-ferries:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        playwright install chromium
        playwright install-deps chromium
    
    - name: Run ferry check
      env:
        SIMPLEPUSH_KEY: ${{ secrets.SIMPLEPUSH_KEY }}
        SIMPLEPUSH_PASSWORD: ${{ secrets.SIMPLEPUSH_PASSWORD }}
        SIMPLEPUSH_SALT: ${{ secrets.SIMPLEPUSH_SALT }}
        WSF_USERNAME: ${{ secrets.WSF_USERNAME }}
        WSF_PASSWORD: ${{ secrets.WSF_PASSWORD }}
        FERRY_REQUESTS: ${{ secrets.FERRY_REQUESTS }}
        GITHUB_ACTIONS: true
      run: python ferry_bot.py
    
    - name: Upload notification state
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: notification-state
        path: /tmp/ferry_bot_*.json
        retention-days: 7